# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0003_auto_20170309_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets_app',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(default=None, dim=3, srid=4326),
        ),
        migrations.AddField(
            model_name='users_app',
            name='bot',
            field=models.BooleanField(default=None),
        ),
    ]
