# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0004_auto_20170309_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_app',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
