# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0007_auto_20170309_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_app',
            name='retweeted_status_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
