# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0008_auto_20170309_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_app',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, dim=3, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='tweets_app',
            name='in_reply_to_status_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tweets_app',
            name='in_reply_to_user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweets_app',
            name='retweeted_status_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
