# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0010_auto_20170309_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_app',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326, verbose_name='coordinates'),
        ),
    ]
