# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0011_auto_20170309_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_app',
            name='geo',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
