# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0012_auto_20170309_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_app',
            name='geo',
            field=models.CharField(max_length=200),
        ),
    ]
