# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0014_auto_20170309_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers_app',
            name='source_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='followers_app',
            name='target_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='friends_app',
            name='source_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='friends_app',
            name='target_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users_app',
            name='favourites_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users_app',
            name='followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users_app',
            name='friends_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users_app',
            name='listed_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users_app',
            name='statuses_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
