# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0018_auto_20170309_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_app',
            name='bot',
            field=models.NullBooleanField(default=None),
        ),
    ]
