# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0020_auto_20170309_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_app',
            name='profile_background_image_url_https',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
