# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0021_auto_20170309_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_app',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
