# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0022_auto_20170309_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets_app',
            name='lang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
