# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0023_tweets_app_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('positive', models.IntegerField(blank=True, default=0, null=True)),
                ('neutral', models.IntegerField(blank=True, default=0, null=True)),
                ('negative', models.IntegerField(blank=True, default=0, null=True)),
                ('bot', models.NullBooleanField(default=0)),
            ],
        ),
    ]
