# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltraining', '0024_sentiment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sentiment',
            new_name='sentiment_app',
        ),
    ]
