# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_app',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='users_app',
            name='updated',
        ),
        migrations.AlterField(
            model_name='users_app',
            name='id',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
