# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170319_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets_app',
            name='reply_count',
        ),
        migrations.RemoveField(
            model_name='tweets_app',
            name='retweeted_status_id',
        ),
        migrations.AddField(
            model_name='tweets_app',
            name='lang',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweets_app',
            name='in_reply_to_screen_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweets_app',
            name='in_reply_to_user_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tweets_app',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
