# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170320_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets_app',
            name='place',
        ),
    ]
