# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_tweets_app_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers_app',
            fields=[
                ('id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('screen_name', models.CharField(blank=True, max_length=200, null=True)),
                ('statuses_count', models.IntegerField(blank=True, default=0, null=True)),
                ('followers_count', models.IntegerField(blank=True, default=0, null=True)),
                ('friends_count', models.IntegerField(blank=True, default=0, null=True)),
                ('favourites_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
