# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_followers_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers_app',
            name='following_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
